steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    dir: "server"
    entrypoint: "gcloud"
    args: ["app", "deploy", "app.yaml", "--quiet"]

options:
  logging: CLOUD_LOGGING_ONLY

timeout: "1200s"