runtime: nodejs20 

env: standard  # Use the standard environment

instance_class: F2  # Adjust based on your resource needs

handlers:
  # Handle API routes (e.g., /api)
  - url: /api/.*
    script: auto